/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIndexRouteImport } from './routes/note/index'
import { Route as NoteNoteIdRouteImport } from './routes/note/$noteId'
import { Route as NoteNoteIdEditRouteImport } from './routes/note/$noteId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdEditRoute = NoteNoteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NoteNoteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/note/$noteId': typeof NoteNoteIdRouteWithChildren
  '/note/': typeof NoteIndexRoute
  '/note/$noteId/edit': typeof NoteNoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/note/$noteId': typeof NoteNoteIdRouteWithChildren
  '/note': typeof NoteIndexRoute
  '/note/$noteId/edit': typeof NoteNoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/note/$noteId': typeof NoteNoteIdRouteWithChildren
  '/note/': typeof NoteIndexRoute
  '/note/$noteId/edit': typeof NoteNoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/note/$noteId' | '/note/' | '/note/$noteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/note/$noteId' | '/note' | '/note/$noteId/edit'
  id: '__root__' | '/' | '/note/$noteId' | '/note/' | '/note/$noteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteNoteIdRoute: typeof NoteNoteIdRouteWithChildren
  NoteIndexRoute: typeof NoteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId/edit': {
      id: '/note/$noteId/edit'
      path: '/edit'
      fullPath: '/note/$noteId/edit'
      preLoaderRoute: typeof NoteNoteIdEditRouteImport
      parentRoute: typeof NoteNoteIdRoute
    }
  }
}

interface NoteNoteIdRouteChildren {
  NoteNoteIdEditRoute: typeof NoteNoteIdEditRoute
}

const NoteNoteIdRouteChildren: NoteNoteIdRouteChildren = {
  NoteNoteIdEditRoute: NoteNoteIdEditRoute,
}

const NoteNoteIdRouteWithChildren = NoteNoteIdRoute._addFileChildren(
  NoteNoteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteNoteIdRoute: NoteNoteIdRouteWithChildren,
  NoteIndexRoute: NoteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
